/*PACIENTE*/
CREATE TABLE [PACIENTE] ( 
COD_PACIENTE INT, 
SEXO CHAR(1), 
DATA_NASCIMENTO DATE,
DATA_SINTOMAS DATE,
PRIMARY KEY (COD_PACIENTE) 
);

INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(1, "M", "1995-11-30", "2021-1-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(2, "F", "1933-6-4", "2021-2-14");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(3, "F", "1959-3-25", "2021-2-7");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(4, "F", "1981-7-8", "2021-2-11");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(5, "M", "2013-1-3", "2021-2-22");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(6, "M", "1957-12-18", "2021-1-8");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(7, "F", "1995-5-23", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(8, "F", "1948-7-27", "2021-1-20");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(9, "F", "1964-4-22", "2021-2-4");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(10, "M","1984-6-5", "2021-2-1");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(11, "M", "1965-4-16", "2021-2-26");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(12, "M", "1972-11-05", "2021-04-01");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(13, "M", "1971-4-10", "2021-1-31");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(14, "M", "1985-2-22", "2021-1-25");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(15, "F", "1965-5-20", "2021-1-11");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(16, "M", "1978-4-11", "2021-2-15");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(17, "M", "1962-6-19", "2021-1-10");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(18, "F", "1971-10-12",	"2021-1-7");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(19, "M", "1975-12-12", "2021-1-7");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(20, "M", "1977-9-8", "2021-1-20");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(21, "M", "1948-1-1", "2021-2-8");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(22,	"M", "1953-11-17", "2021-2-26");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(23,	"M", "1976-11-28", "2021-1-31");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(24, "M", "1984-4-2", "2021-2-17");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(25, "M", "1957-3-29", "2021-1-26");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(26, "M", "1938-2-21", "2021-2-2");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(27, "M", "1953-10-14", "2021-1-27");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(28,	"M", "1964-6-7", "2021-2-10");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(29, "M", "2020-10-7", "2021-2-22");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(30, "M", "1980-11-9", "2021-2-14");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(31, "M", "2005-3-30", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(32, "F", "1958-9-16", "2021-2-7");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(33, "F", "1985-3-13", "2021-1-19");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(34, "F", "1993-7-14", "2021-2-26");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(35,	"M", "1966-5-3", "2021-1-23");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(36, "F", "1966-4-29", "2021-1-9");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(37,	"F", "1961-9-30", "2021-1-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(38,	"F", NULL,	"2021-1-13");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(39,	"M", "1986-8-19", "2021-2-13");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(40, "M", "1970-7-19", "2021-2-25");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(41, "M", "1966-11-14", "2021-2-9");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(42,	"F", "1961-11-21", "2021-1-23");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(43, "F", "1934-7-7", "2021-1-29");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(44, "M", "1979-5-9", "2021-2-25");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(45, "M", "1959-5-31", "2021-2-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(46, "M", "1946-3-20", "2021-2-9");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(47,	"M", "1949-10-28", "2021-2-19");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(48, "M", "1993-6-18", "2021-2-15");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(49,	"M", "1978-11-5", "2021-2-18");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(50, "F", "1980-10-19", "2021-1-23");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(51, "F", "1958-2-26", "2021-1-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(52, "M", "1961-7-4", "2021-1-20");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(53, "F", "1955-1-28", "2021-2-18");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(54, "F", "2010-6-9", "2021-1-9");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(55, "F", "1959-1-20", "2021-2-16");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(56,	"M", "1967-4-21", "2021-2-14");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(57, "M", "1960-7-24", "2021-1-11");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(58, "M", "1972-8-1", "2021-2-11");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(59, "M", "1983-7-20", "2021-2-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(60, "F", "1958-7-12", "2021-2-11");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(61, "M", "1979-11-12", "2021-1-22");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(62, "F", "2001-9-7", "2021-2-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(63, "F", "1946-12-2", "2021-2-13");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(64, "M", "1977-4-21", "2021-2-16");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(65, "F", "1959-12-10", "2021-1-27");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(66, "M", "1971-3-5", "2021-2-23");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(67, "F", "1947-10-4", "2021-1-20");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(68, "F", "1955-5-30", "2021-1-10");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(69, "M", "1988-9-28", "2021-1-28");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(70, "M", "1973-3-7", "2021-2-2");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(71, "M", "1970-11-28", "2021-1-28");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(72, "M", "1965-8-1", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(73, "M", "1960-1-17", "2021-1-25");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(74, "F", "1946-2-11", "2021-1-6");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(75, "M", "1959-3-4", "2021-2-15");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(76, "M", "1968-9-25", "2021-1-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(77, "M", "1970-5-21", "2021-1-8");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(78, "M", "1979-9-23", "2021-2-12");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(79, "M", "1979-12-6", "2021-2-19");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(80, "F", "1983-6-30", "2021-1-9");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(81, "M", "1992-9-4", "2021-1-21");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(82, "M", "1930-2-10", "2021-1-25");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(83, "F", "1944-7-20", "2021-1-13");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(84, "M", "2020-10-26", "2021-1-4");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(85, "F", "1974-8-19", "2021-1-4");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(87, "M", "1954-5-31", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(88, "F", "1936-1-11", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(89, "F", "1940-12-18", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(90, "F", "1967-7-14", "2021-1-5");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(91,	"F", "1930-3-22", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(92, "M", "1948-3-7", "2021-1-5");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(93, "M", "2019-11-14", "2021-1-5");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(94, "M", "1969-12-1", "2021-1-9");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(95,	"F", "1975-7-26", "2021-1-7");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(96, "F", "1950-9-14", "2021-1-4");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(97, "F", "1969-9-24", "2021-1-5");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(98, "M", "1980-6-23", "2021-1-4");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(99, "M", "2005-12-1", "2021-1-3");
INSERT INTO PACIENTE(COD_PACIENTE, SEXO, DATA_NASCIMENTO, DATA_SINTOMAS) VALUES(100, "F", "1969-9-15", "2021-1-3");



CREATE TABLE [CONCLUSAO](
COD_PACIENTE INT,
DATA_CONCLUSAO DATE,
EVOLUCAO_CASO VARCHAR(45),
PRIMARY KEY (COD_PACIENTE), 
FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTE(COD_PACIENTE),

);

/*EVOLUCAO
1-Cura
2-�bito
9-Ignorado*/

INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (1, "2021-1-27", "Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (3,"2021-2-26","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (5,"2021-2-25","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (6,"2021-1-19","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (8,"2021-1-3","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (9,"2021-2-25","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (10,"2021-3-2","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (12,"2021-29-01","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (14,"2021-2-13","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (17,"2021-1-27","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (18,"2021-2-11","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (19,"2021-2-4","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (20,"2021-1-27","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (21,"2021-2-14","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (23,"2021-2-7","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (25,"2021-2-10", "Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (28,"2021-2-26","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (32,"2021-2-25","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (35,"2021-2-4","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (36,"2021-2-22","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (37,"2021-1-27","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (38,"2021-1-24","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (42,"2021-2-7","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (43,"2021-2-5","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (46,"2021-2-21","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (47,"2021-2-25","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (48,"2021-3-4","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (49,"2021-2-20","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (51,"2021-2-19","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (52,"2021-2-10","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (61,"2021-2-1","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (63,"2021-2-28","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (69,"2021-2-12","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (73,"2021-2-6","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (74,"2021-1-21","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (75,"2021-2-25","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (76,"2021-1-28","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (77,"2021-1-14","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (78,"2021-3-1","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (80,"2021-1-22","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (82,"2021-2-1","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (83,"2021-2-14","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (84,"2021-1-4","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (88,"2021-1-5","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (91,"2021-1-10","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (92,"2021-1-7","�bito");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (94,"2021-1-13","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (96,"2021-1-21","Cura");
INSERT INTO CONCLUSAO(COD_PACIENTE, DATA_CONCLUSAO, EVOLUCAO_CASO) VALUES (97,"2021-1-21","�bito");



/*SINTOMAS*/

/*
10 - Febre
20 - Tosse
30 - Perca de Olfato
40 - Perca de Paladar
50 - Dispneia (falta de ar)
*/

CREATE TABLE [SINTOMAS](
COD_SINTOMA INT,
NOME_SINTOMA VARCHAR(45),
PRIMARY KEY (COD_SINTOMA)
);

INSERT INTO SINTOMAS(COD_SINTOMA, NOME_SINTOMA) VALUES(10, "Febre");
INSERT INTO SINTOMAS(COD_SINTOMA, NOME_SINTOMA) VALUES(20, "Tosse");
INSERT INTO SINTOMAS(COD_SINTOMA, NOME_SINTOMA) VALUES(30, "Perca de Olfato");
INSERT INTO SINTOMAS(COD_SINTOMA, NOME_SINTOMA) VALUES(40, "Perca de Paladar");
INSERT INTO SINTOMAS(COD_SINTOMA, NOME_SINTOMA) VALUES(50, "Dispneia");


CREATE TABLE [PACIENTES_SINTOMAS] ( 
COD_SINTOMA INT,
COD_PACIENTE INT,
FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTE(COD_PACIENTE),
FOREIGN KEY (COD_SINTOMA) REFERENCES SINTOMAS(COD_SINTOMA),
PRIMARY KEY(COD_PACIENTE,COD_SINTOMA)
);



INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(1,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(3,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(3,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(3,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(4,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(4,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(4,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(4,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(5,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(5,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(6,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(7,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(7,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(7,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(7,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(7,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(8,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(8,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(8,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(9,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(9,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(9,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(10,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(10,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(10,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(11,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(11,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(12,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(12,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(13,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(13,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(14,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(14,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(14,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(15,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(16,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(16,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(16,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(16,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(17,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(17,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(17,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(18,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(18,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(19,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(20,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(20,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(21,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(22,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(22,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(23,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(23,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(23,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(24,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(24,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(24,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(25,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(25,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(26,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(26,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(26,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(27,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(27,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(28,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(28,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(28,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(29,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(29,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(30,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(30,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(30,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(30,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(32,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(32,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(32,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(32,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(32,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(33,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(33,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(33,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(35,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(35,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(35,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(36,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(36,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(36,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(36,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(36,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(37,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(37,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(37,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(37,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(38,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(39,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(39,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(39,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(40,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(40,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(40,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(41,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(41,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(41,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(41,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(41,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(42,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(42,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(43,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(43,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(43,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(44,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(44,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(45,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(45,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(45,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(46,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(47,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(48,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(48,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(49,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(49,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(50,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(50,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(51,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(51,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(52,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(52,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(52,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(52,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(53,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(53,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(53,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(55,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(55,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(55,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(55,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(56,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(56,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(56,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(56,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(56,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(57,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(57,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(58,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(58,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(58,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(59,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(59,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(60,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(61,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(62,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(62,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(63,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(64,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(64,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(64,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(65,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(65,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(66,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(66,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(66,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(67,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(68,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(69,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(69,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(69,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(69,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(69,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(70,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(70,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(71,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(71,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(71,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(71,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(71,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(72,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(72,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(73,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(73,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(74,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(74,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(75,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(76,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(76,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(76,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(77,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(77,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(78,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(78,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(78,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(79,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(79,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(79,30);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(79,40);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(80,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(81,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(82,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(82,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(83,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(83,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(84,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(84,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(85,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(85,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(85,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(86,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(87,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(88,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(88,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(89,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(89,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(90,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(90,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(91,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(91,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(92,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(93,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(95,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(96,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(97,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(97,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(97,50);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(98,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(99,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(99,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(100,10);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(100,20);
INSERT INTO PACIENTES_SINTOMAS(COD_PACIENTE, COD_SINTOMA) VALUES(100,50);




/*FATORES DE RISCO*/

/*
100 Doen�a Cardiovascular
200 Asma
300 Diabetes
400 Obesidade
*/

CREATE TABLE [FATOR_RISCO](
COD_FATOR_RISCO INT,
NOME_FATOR_RISCO VARCHAR(45),
PRIMARY KEY (COD_FATOR_RISCO)
);


INSERT INTO FATOR_RISCO(COD_FATOR_RISCO, NOME_FATOR_RISCO) VALUES (100, "Doen�a Cardiovascular");
INSERT INTO FATOR_RISCO(COD_FATOR_RISCO, NOME_FATOR_RISCO) VALUES (200, "Asma");
INSERT INTO FATOR_RISCO(COD_FATOR_RISCO, NOME_FATOR_RISCO) VALUES (300, "Diabetes");
INSERT INTO FATOR_RISCO(COD_FATOR_RISCO, NOME_FATOR_RISCO) VALUES (400, "Obesidade");



CREATE TABLE [PACIENTES_FATOR_RISCO](
COD_FATOR_RISCO INT,
COD_PACIENTE INT,
FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTE(COD_PACIENTE),
FOREIGN KEY (COD_FATOR_RISCO) REFERENCES FATOR_RISCO(COD_FATOR_RISCO),
PRIMARY KEY (COD_PACIENTE,COD_FATOR_RISCO)
);


INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(2,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(3,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(3,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(6,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(8,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(9,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(9,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(9,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(11,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(14,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(16,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(17,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(18,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(19,200);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(19,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(25,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(28,200);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(30,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(33,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(35,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(36,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(36,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(37,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(39,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(41,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(43,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(46,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(47,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(49,200);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(52,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(54,200);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(56,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(57,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(60,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(65,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(65,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(67,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(67,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(68,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(74,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(76,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(77,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(78,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(82,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(83,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(83,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(85,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(85,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(87,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(87,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(88,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(88,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(89,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(90,100);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(90,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(90,400);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(91,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(96,300);
INSERT INTO PACIENTES_FATOR_RISCO(COD_PACIENTE, COD_FATOR_RISCO) VALUES(100,100);





/*VIAGEM*/
CREATE TABLE [DESTINO_VIAGEM] ( 
COD_DESTINO INT, 
NOME VARCHAR(45),
PRIMARY KEY (COD_DESTINO),
);

INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(101, "Brasil");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(102, "Paraguai");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(103, "Ciudad Del Este");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(104, "Roraima");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(105, "Caldas Novas/GO");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(106, "Chile");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(107, "Rio de Janeiro");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(108, "Ijui");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(109, "Jequie");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(110, "Bras�lia");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(111, "Ponta Pora");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(112, "Manaus");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(113, "S�o Paulo");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(114, "Free Shopping");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(115, "Portugal");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(116, "Porto");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(117, "Parana");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(118, "Londres");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(119, "M�xico");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(120, "Estados Unidos da Am�rica");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(121, "Curitiba");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(122, "Bol�via");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(123, "Porto Alegre");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(124, "Equador");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(125, "Pernambuco");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(126, "Argentina");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(127, "Regi�o dos Lagos");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(128, "Itapoa");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(129, "Belem/PA");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(130, "Pedro Juan");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(131, "Eti�pia");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(132, "Salto de Guaira");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(133, "China, Republica Popular");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(134, "Ponte Serrada");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(135, "Porto Velho");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(136, "Robore");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(137, "Foz do Igua�u");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(138, "Cotia/SP");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(139, "Estado de Mato Grosso");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(140, "Puente Sinho");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(141, "Brusque");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(142, "Ilheus");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(143, "Amazonas");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(144, "Itabuna");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(145, "Goi�nia");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(146, "Huston");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(147, "Bela Vista Norte");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(148, "Puerto Soares");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(149, "Itajai");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(150, "Itaqui");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(151, "Salto do Araguaia");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(151, "Curitiba");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(152, "Dallas-Texas");
INSERT INTO DESTINO_VIAGEM(COD_DESTINO, NOME) VALUES(153, "Carolina do Sul");




CREATE TABLE [VIAGEM] ( 
COD_VIAGEM INT, 
DATA_IDA DATE,
DATA_RETORNO DATE,
PRIMARY KEY (COD_VIAGEM),
FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTE(COD_PACIENTE),
FOREIGN KEY (COD_DESTINO) REFERENCES DESTINO_VIAGEM(COD_DESTINO)
);

INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1111, 2021-01-15, 2021-01-17, 1, 102);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1112, 2021-02-10, 2021-02-10, 2, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1113, 2021-02-05, 2021-02-07, 3, 103);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1114, 2021-02-02, 2021-02-09, 4, 104);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1115, 2021-02-18, 2021-02-21, 5, 105);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1116, 2020-12-30, 2021-01-08, 6, 106);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1117, 2020-12-16, 2021-01-03, 7, 107);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1118, 2021-01-02, 2021-01-03, 8, 108);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1119, 2021-02-01, 2021-02-12, 9, 109);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1120, 2021-02-05, 2021-02-15, 10, 110);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1121, 2021-02-24, 2021-02-25, 11, 111);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1122, 2020-12-23, 2021-01-07, 12, 112);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1123, 2021-02-02, 2021-02-10, 13, 113);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1124, 2021-02-24, 2021-02-25, 14, 102);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1125, 2020-12-31, 2021-01-02, 15, 114);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1126, 2021-02-13, 2021-02-13, 16, 115);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1127, 2020-08-30, 2021-01-08, 17, 116);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1128, 2021-01-01, 2021-01-10, 18, 117);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1129, 2021-01-06, 2021-01-10, 19, 102);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1130, 2021-01-14, 2021-01-21, 20, 118);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1131, 2021-02-07, 2021-02-09, 21, 102);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1132, 2021-02-22, 2021-03-02, 22, 110);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1133, 2020-12-16, 2021-01-18, 23, 119);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1134, 24, 120);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1135, 2021-01-25, 2021-01-28, 25, 121);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1136, 2021-01-28, 2021-01-28, 26, 122);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1137, 2021-01-24, 2021-01-27, 27, 123);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1138, 2021-01-30, 2021-02-06, 28, 124);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1139, 2021-01-10, 2021-01-20, 29, 125);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1140, 2021-02-12, 2021-02-23, 30, 126);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1141, 2021-01-07, 2021-01-10, 31, 127);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1142, 2020-12-22, 2021-02-09, 32, 112);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1143, 2021-01-28, 2021-02-05, 33, 101);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1144, 34, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1145, 2020-01-30, 2020-11-30, 35, 128);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1146, 2021-01-01, 2021-01-10, 36, 107);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1147, 2021-01-05, 2021-01-11, 37, 129);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1148, 38, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1149, 2021-01-19, 2021-02-08, 39, 113);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1150, 2021-02-23, 2021-02-25, 40, 128);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1151, 2021-02-08, 2021-02-13, 41, 113);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1152, 2021-01-23, 2021-01-23, 42, 130);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1153, 43, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1154, 2021-01-13, 2021-02-28, 44, 131);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1155, 2021-01-15, 2021-01-28, 45, 126);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1156, 46, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1157, 2021-02-19, 2021-02-19, 47, 132);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1158, 2021-02-04, 2021-02-10, 48, 133);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1159, 2021-02-17, 2021-02-18, 49, 134);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1160, 2021-01-26, 2021-02-01, 50, 135);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1161, 2020-12-23, 2020-12-26, 51, 136);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1162, 2021-01-04, 2021-01-10, 52, 137);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1163, 2021-02-12, 2021-02-12, 53, 106);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1164, 2020-12-22, 2020-12-26, 54, 138);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1165, 2021-02-12, 2021-02-13, 55, 139);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1166, 2021-02-11, 2021-02-11, 56, 121);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1167, 2021-01-16, 2021-01-16, 57, 140);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1168, 2021-02-08, 2021-02-08, 58, 132);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1169, 2020-02-29, 2020-03-03, 59, 126);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1170, 60, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1171, 2021-01-13, 2021-01-17, 61, 141);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1172, 2021-02-05, 2021-02-06, 62, 102);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1173, 2021-02-13, 2021-02-15, 63, 102);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1174, 64, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1175, 2021-01-25, 2021-01-30, 65, 142);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1176, 2021-02-19, 2021-02-27, 66, 143);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1177, 67, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1178, 2020-12-22, 2021-01-10, 68, 144);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1179, 2021-01-26, 2021-01-28, 69, 103);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1180, 2021-01-25, 2021-02-02, 70, 102);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1181, 2021-01-25, 2021-01-29, 71, 145);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1182, 2020-12-01, 2020-12-22, 72, 146);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1183, 73, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1184, 2021-01-07, 2021-01-07, 74, 147);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1185, 2021-02-25, 2021-02-25, 75, 148);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1186, 2021-01-11, 2021-01-14, 76, 107);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1187, 2021-01-07, 2021-01-07, 77, 149);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1188, 2021-02-08, 2021-02-10, 78, 150);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1189, 2021-02-08, 2021-02-08, 79, 151);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1190, 2021-01-04, 2021-01-09, 80, 126);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1191, 2021-01-17, 2021-01-18, 81, 101);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1192, 2020-10-28, 2020-12-11, 82, 152);
INSERT INTO VIAGEM(COD_VIAGEM, DATA_IDA, DATA_RETORNO, COD_PACIENTE, COD_DESTINO) VALUES(1193, 2020-10-28, 2020-12-11, 82, 153);
INSERT INTO VIAGEM(COD_VIAGEM, COD_PACIENTE, COD_DESTINO) VALUES(1194, 83, 101);


/*HOSPITAL - MUNICIPIO - INTERNA��O*/
CREATE TABLE [MUNICIPIO](
COD_MUNICIPIO INT,
NOME_MUNICIPIO VARCHAR(45),
UF_MUNICIPIO CHAR(2),
PRIMARY KEY (COD_MUNICIPIO)
);

INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(421720,"SAO MIGUEL DO OESTE","SC");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(412710,"TELEMACO BORBA","PR");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(431690,"SANTA MARIA","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(354140,"PRESIDENTE PRUDENTE","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(355710,"VOTUPORANGA","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(432240,"URUGUAIANA","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(510760,"RONDONOPOLIS","MT");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(431800,"SAO BORJA","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(293330,"VITORIA DA CONQUISTA","BA");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(520870,"GOIANIA","GO");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(313670,"JUIZ DE FORA","MG");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(292740,"SALVADOR","BA");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(355510,"TUPI PAULISTA","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(355410,"TAUBATE","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(315180,"POCOS DE CALDAS","MG");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(350930,"CAJOBI","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(430440,"CANELA","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(420460,"CRICIUMA","SC");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(431680,"SANTA CRUZ DO SUL","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(351880,"GUARULHOS","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(431490,"PORTO ALEGRE","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(411850,"PATO BRANCO","PR");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(420550,"FRAIBURGO","SC");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(355030,"SAO PAULO","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(431720,"SANTA ROSA","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(330455,"RIO DE JANEIRO","RJ");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(353440,"OSASCO","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(230700,"JAGUARUANA","CE");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(411910,"PIEN","PR");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(270630,"PALMEIRA DOS INDIOS","AL");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(410690,"CURITIBA","PR");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(430760,"ESTANCIA VELHA","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(230440,"FORTALEZA","CE");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(420380,"CANOINHAS","SC");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(500450,"ITAPORA","MS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(520800,"FORMOSA","GO");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(311860,"CONTAGEM","MG");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(421050,"MARAVILHA","SC");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(250400,"CAMPINA GRANDE","PB");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(211130,"SAO LUIS","MA");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(410290,"BITURUNA","PR");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(110040,"ALTO PARAISO","RO");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(500320,"CORUMBA","MS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(353540,"PANORAMA","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(500210,"BELA VISTA","MS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(500370,"DOURADOS","MS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(350570,"BARUERI","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(150680,"SANTAREM","PA");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(412770,"TOLEDO","PR");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(410830,"FOZ DO IGUACU","PR");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(420540,"FLORIANOPOLIS","SC");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(313420,"ITUIUTABA","MG");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(430470,"CARAZINHO","RS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(521180,"JARAGUA","GO");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(314790,"PASSOS","MG");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(351340,"CRUZEIRO","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(421830,"TRES BARRAS","SC");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(354990,"SAO JOSE DOS CAMPOS","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(313240,"ITAJUBA","MG");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(350950,"CAMPINAS","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(314070,"MATEUS LEME","MG");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(280030,"ARACAJU","SE");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(355280,"TABOAO DA SERRA","SP");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(500270,"CAMPO GRANDE","MS");
INSERT INTO MUNICIPIO(COD_MUNICIPIO, NOME_MUNICIPIO, UF_MUNICIPIO) VALUES(261160,"RECIFE","PE");


CREATE TABLE [HOSPITAL](
COD_HOSPITAL INT,
NOME_HOSPITAL VARCHAR(45),
PRIMARY KEY (COD_HOSPITAL),
FOREIGN KEY (COD_MUNICIPIO) REFERENCES MUNICIPIO(COD_MUNICIPIO)
);

INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(6683134,"HOSPITAL REGIONAL TEREZINHA GAIO BASSO",421720);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2740435,"IDF",412710);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(9575936,"HOSPITAL REGIONAL DE SANTA MARIA",431690);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2080516,"HOSPITAL GERAL IAMADA PRES PRUDENTE",354140);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2084309,"CASA DE SAUDE",355710);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2248190,"SANTA CASA DE URUGUAIANA",432240);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(7068743,"PRONTO ATENDIMENTO UNIMED RONDONOPOLIS",510760);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2248298,"HOSPITAL INFANTIL",431800);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2407205,"SAMUR",293330);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(86126,"HOSPITAL DE ENFRENTAMENTO AO CORONAVIRUS DE GOIANIA",520870);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2153882,"SANTA CASA DE MISERICORDIA DE JUIZ DE FORA",313670);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(3808,"HOSPITAL SAO RAFAEL",292740);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2081385,"SANTA CASA DE TUPI PAULISTA",355510);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(4050665,"UPA CENTRAL",355410);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2129566,"HOSPITAL SANTA LUCIA HOSPITAL DO CORACAO",315180);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2081296,"HOSPITAL JOAO DEPIERI DE CAJOBI",350930);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2235609,"HOSPITAL DE CANELA",430440);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(5712068,"HOSPITAL UNIMED CRICIUMA",420460);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2255936,"HOSPITAL ANA NERY",431680);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(9400109,"UPA CUMBICA",351880);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2078147,"HOSPITAL E MATERNIDADE NOSSA SENHORA DAS GRACAS",354140);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2237601,"HOSPITAL DE CLINICAS",431490);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(17868,"POLICLINICA PATO BRANCO",411850);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL) VALUES(9051422,"UPA III 26 DE AGOSTO");
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(7274351,"ACENI",420550);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2058391,"HOSPITAL ISRAELITA ALBERT EINSTEIN",355030);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(5420938,"HOSP MUN CARMEN PRUDENTE",355030);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2254611,"HOSPITAL VIDA SAUDE",431720);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(6631169,"SMS UPA 24 H ENGENHO DE DENTRO AP 32",330455);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(8028,"HOSPITAL MUNICIPAL ANTONIO GIGLIO",353440);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2560976,"HOSPITAL MATERNIDADE NOSSA SENHORA DA EXPECTACAO",230700);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL) VALUES(3663051,"HOSPITAL MUNICIPAL DE ARAGUAINA");
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(7424981,"FUNDACAO HARRY GUIDO GREIPEL",411910);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2010631,"HOSPITAL REGIONAL SANTA RITA E MATERNIDADE SANTA OLIMPIA",270630);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2384299,"COMPLEXO HOSPITAL DE CLINICAS",410690);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2707632,"HOSPITAL MUNICIPAL GETULIO VARGAS",430760);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(3189546,"HOSPITAL SAO CARLOS",230440);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2491249,"HOSPITAL SANTA CRUZ DE CANOINHAS",420380);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2651505,"HOSPITAL MUNICIPAL LOURIVAL NASCIMENTO DA SILVA",500450);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2534967,"HOSPITAL REGIONAL DE FORMOSA DR CESAR SAAD FAYAD",520800);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2200473,"HOSPITAL MUNICIPAL DE CONTAGEM",311860);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2538180,"HOSPITAL SAO JOSE DE MARAVILHA",421050);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(3006204,"CLINICA SANTA CLARA",250400);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL) VALUES(7541228,"UNIDADE DE PRONTO ATENDIMENTO UPA");
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2459736,"CEMED",211130);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2549263,"HOSPITAL SAO VICENTE DE PAULA",410290);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2808676,"HOSPITAL DE PEQUENO PORTE OSVALDO CRUZ",110040);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2558815,"PRONTO SOCORRO MUNICIPAL DE CORUMBA",500320);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(6858317,"SES RJ UPA 24H COPACABANA",330455);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2079283,"SANTA CASA DE PANORAMA",353540);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2376458,"HOSPITAL SAO VICENTE DE PAULA",500210);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2710935,"EBSERH HOSPITAL UNIVERSITARIO GRANDE DOURADOS",500370);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(3272591,"HOSPITALIS",350570);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(7530005,"UNIDADE DE PRONTO ATENDIMENTO UPA 24 HORAS",150680);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(4056752,"HOESP",412770);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(5061989,"HOSPITAL MUNICIPAL PADRE GERMANO LAUCK",410830);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(5585422,"HOSPITAL REGIONAL DO BAIXO AMAZONAS DO PA DR WALDEMAR PENNA",150680);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2691841,"HOSPITAL GOVERNADOR CELSO RAMOS",420540);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2121921,"UNIDADE BASICA DE SAUDE IRENE THEODORA DE OLIVEIRA",313420);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2262274,"HOSPITAL DE CARIDADE DE CARAZINHO",430470);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2361949,"HOSPITAL ESTADUAL DE JARAGUA SANDINO DE AMORIM",521180);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2775999,"IRMANDADE DA SANTA CASA DE MISERICORDIA DE PASSOS",314790);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2376334,"SANTA CASA DE CORUMBA",500320);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL) VALUES(2078503,"SANTA CASA DE PENAPOLIS");
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2024594,"VISAVE",351340);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2490935,"HOSPITAL FELIX DA COSTA GOMES",421830);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2081628,"HOSPITAL CARLOS CHAGAS",351880);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL) VALUES(2588188,"HOSPITAL E MATERNIDADE PADRE TEZZA");
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2540355,"HOSPITAL SAO JOAO BATISTA HSJB",420460);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2237849,"INSTITUTO DE CARDIOLOGIA",431490);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2082225,"HOSPITAL KATIA DE SOUZA RODRIGUES TAIPAS SAO PAULO",355030);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(6595197,"HOSPITAL DO SUBURBIO",292740);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(9491252,"DR RUBENS SAVASTANO HOSPITAL REGIONAL DE SAO JOSE DOS CAMPOS",354990);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2208857,"AISI HOSPITAL DE CLINICAS DE ITAJUBA",313240);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2082128,"HOSPITAL E MATERNIDADE CELSO PIERRO",350950);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(7061838,"MATEUS LEME UPA 24 HORAS TIAGO CARDOSO SANTOS",314070);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(3841375,"HOSPITAL MUNICIPAL ZONA NORTE DR NESTOR PIVA",280030);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2785188,"UNIDADE MISTA DE SAUDE DE TABOAO DA SERRA",355280);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2080338,"HOSPITAL GERAL DE GUARULHOS PROF DR WALDEMAR DE CARVALHO",351880);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(9725,"HOSPITAL REGIONAL DE MATO GROSSO DO SUL",500270);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(3824802,"SAO LUIZ UNIDADE MORUMBI",355030);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2084341,"HOSP STA MAGGIORE BELA VISTA",355030);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2298724,"SES RJ HOSPITAL ESTADUAL ANCHIETA",330455);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL) VALUES(2472376,"UNIDADE MISTA DE SAUDE");
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2755130,"HOSPITAL DOMINGOS LEONARDO CERAVOLO PRESIDENTE PRUDENTE",354140);
INSERT INTO HOSPITAL(COD_HOSPITAL, NOME_HOSPITAL, COD_MUNICIPIO) VALUES(2819279,"HOSPITAL DE BOA VIAGEM",261160);


CREATE TABLE [INTERNACAO](
COD_INTERNACAO INT,
DATA_INTERNACAO DATE,
SUPORTE_VENTILATORIO VARCHAR(45),
PRIMARY KEY(COD_INTERNACAO),
FOREIGN KEY (COD_PACIENTE) REFERENCES PACIENTE(COD_PACIENTE),
FOREIGN KEY (COD_HOSPITAL) REFERENCES HOSPITAL(COD_HOSPITAL)
);

INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(1, 2021-01-24, "Sim", 1, 6683134);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(2, 2021-02-20, "Sim", 2, 2740435);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(3, 2021-02-14, "Sim", 3, 9575936);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(4, 2021-02-15, "Sim", 4, 2080516);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(5, 2021-02-23, "N�o", 5, 2084309);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(6, 2021-01-08, "Sim", 6, 2248190);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(7, 2021-01-13, "N�o", 7, 7068743);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(8, 2021-01-25, "N�o", 8, 2248298);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(9, 2021-02-14, "Sim", 9, 2407205);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(10, 2021-02-15, "Sim", 10, 86126);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(11, 2021-03-01, "Sim", 11, 7068743);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(12, 2021-01-11, "Sim", 12, 2153882);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(13, 2021-02-11, "Sim", 13, 3808);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(14, 2021-02-09, "Sim", 14, 2081385);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(15, 2021-01-18, "Sim", 15, 4050665);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(16, 2021-02-25, "Sim", 16, 9575936);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(17, 2021-01-16, "Sim", 17, 2129566);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(18, 2021-01-13, "Sim", 18, 2081296);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(19, 2021-01-10, "Sim", 19, 2235609);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(20, 2021-01-23, "N�o", 20, 5712068);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(21, 2021-02-09, "Sim", 21, 2255936);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(22, "Sim", 22, 9400109);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(23, 2021-02-06, "N�o", 23, 2078147);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(24, "Sim", 24, 2237601);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(25, 2021-02-07, "N�o", 25, 17868);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(26, "N�o", 26, 9051422);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(27, 2021-01-31, "N�o", 27, 7274351);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(28, 2021-02-16, "Sim", 28, 2058391);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(29, 2021-02-26, "Sim", 29, 5420938);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(30, 2021-02-23, "Sim", 30, 2254611);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(31, 2021-01-12, "N�o", 31, 6631169);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(32, 2021-02-17, "Sim", 32, 8028);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(33, 2021-01-23, "Sim", 33, 2560976v
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(34, "N�o", 34, 3663051);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(35, 2021-01-31, "Sim", 35, 7424981);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(36, 2021-01-16, "Sim", 36, 2010631);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(37, 2021-01-21, "Sim", 37, 2384299);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(38, 2021-01-14, "Sim", 38, 2707632);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(39, 2021-02-20, "N�o", 39, 3189546);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(40, 2021-02-28, "Sim", 40, 2491249);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(41, 2021-02-14, "Sim", 41, 7424981);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(42, 2021-01-30, "N�o", 42, 2651505);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(43, 2021-02-02, "Sim", 43, 2534967);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(44, 2021-03-03, "Sim", 44, 2200473);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(45, 2021-02-21, "N�o", 45, 2538180);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(46, 2021-02-14, "Sim", 46, 3006204);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(47, "Sim", 47, 7541228);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(48, 2021-02-22, "Sim", 48, 2459736);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(49, 2021-02-18, "Sim", 49, 2549263);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(50, 2021-02-09, "Sim", 50, 2808676);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(51, 2021-01-16, "Sim", 51, 2558815);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(52, 2021-01-28, "Sim", 52, 17868);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(53, 2021-02-24, "Sim", 53, 6858317);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(54, 2021-01-10, "Sim", 54, 5420938);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(55, 2021-03-02, "Sim", 55, 2079283);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(56, 2021-02-18, "Sim", 56, 7424981);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(57, 2021-01-16, "N�o", 57, 2376458);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(58, 2021-02-16, "Sim", 58, 2710935);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(59, 2021-02-12, "N�o", 59, 3272591);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(60, 2021-02-17, "N�o", 60, 7530005);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(61, 2021-01-23, "N�o", 61, 17868);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(62, 2021-02-16, "Sim", 62, 4056752);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(63, 2021-02-15, "Sim", 63, 5061989);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(64, 2021-02-26, "Sim", 64, 5585422);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(65, 2021-02-05, "Sim", 65, 2407205);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(66, 2021-03-03, "Sim", 66, 2691841);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(67, 2021-02-04, "Sim", 67, 2121921);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(68, 2021-01-13, "Sim", 68, 9400109);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(69, 2021-02-08, "N�o", 69, 2262274);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(70, 2021-02-10, "Sim", 70, 9575936);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(71, 2021-02-03, "Sim", 71, 2361949);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(72, 2021-01-19, "Sim", 72, 2775999);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(73, 2021-01-31, "N�o", 73, 7530005);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(74, 2021-01-07, "Sim", 74, 2376458);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(75, 2021-02-25, "Sim", 75, 2376334);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(76, "N�o", 76, 2078503);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(77, 2021-01-09, "Sim", 77, 7424981);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(78, 2021-02-18, "Sim", 78, 2024594);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(79, 2021-02-26, "Sim", 79, 2490935);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(80, 2021-01-14, "N�o", 80, 2081628);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(81, "N�o", 81, 2588188);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(82, 2021-01-26, "Sim", 82, 2540355);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(83, 2021-01-13, "Sim", 83, 2237849);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(84, 2021-01-04, "N�o", 84, 2082225);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(85, 2021-01-04, "N�o", 85, 6595197);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(86, 2021-01-03, "N�o", 86, 9491252);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(87, 2021-01-03, "Sim", 87, 2208857);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(88, 2021-01-03, "Sim", 88, 2082128);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(89, "Sim", 89, 7061838);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(90, "Sim", 90, 3841375);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(91, 2021-01-07, "Sim", 91, 2785188);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(92, 2021-01-07, "Sim", 92, 2080338);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(93, 2021-01-08, "N�o", 93, 9725);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(94, 2021-01-10, "N�o", 94, 3824802);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(95, "N�o", 95, 2588188);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(96, 2021-01-12, "Sim", 96, 2084341);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(97, 2021-01-05, "Sim", 97, 2298724);
INSERT INTO INTERNACAO(COD_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(98, "N�o", 98, 2472376);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(99, 2021-01-06, "N�o", 99, 2755130);
INSERT INTO INTERNACAO(COD_INTERNACAO, DATA_INTERNACAO, SUPORTE_VENTILATORIO, COD_PACIENTE, COD_HOSPITAL) VALUES(100, 2021-01-11, "N�o", 100, 2819279);
